### ISSUE TITLE
[Question] On ScrollView, how to take picture all of it, not only visible part?

### ISSUE THREAD

**Issue by fuatsengul** [gre/react-native-view-shot#70] opened 2017-06-02 15:44 UTC
Hi, I have a long page which user have to scroll down to read all of it. This page is something user want to share on social media, so I need to take a shot whole scrollview content.
So, I've tried to use this package to take the image but it only returns what's visible on screen at the moment, I've also tried snapshotContentContainer option but no luck so far.

**Comment by ihor** [comment] 2017-06-06 20:38
I'm having the same issue. Have you found any solution?

**Comment by fuatsengul** [comment] 2017-06-06 21:01
Sorry, I was working on another part of the app at the moment, please let me know if you find a solution for that. Thanks

**Comment by ihor** [comment] 2017-06-06 21:27
Well, rendering off-screen in a regular ```View``` as suggested here https://github.com/gre/react-native-view-shot/issues/31 works.

**Comment by gre** [comment] 2017-06-06 23:15
mmh yeah so snapshotContentContainer is supposed to solve that. are you screenshoting from the scrollview ref?

**Comment by gre** [comment] 2017-06-07 00:04
maybe there is a bug in the feature https://github.com/gre/react-native-view-shot/issues/47#issuecomment-287363012

**Comment by ihor** [comment] 2017-06-07 20:35
I see the same as described in #47. The content is stretched but cut.

**Comment by gre** [comment] 2017-06-08 03:18
I guess the bug is only on iOS, probably around these lines: https://github.com/gre/react-native-view-shot/blob/9a613da4aac77dda74d58f6836f7934173ee3ffa/ios/RNViewShot.m#L88-L94

  would you like to provide a PR to fix it? (I have bad connectivity right now in China, coming back in 2wks)

**Comment by sachinB94** [comment] 2017-07-26 08:33
Hey, Any update on this? Testing on iOS simulator, facing the same issue.

**Comment by gre** [comment] 2017-07-26 09:58
do you want to try a fix and submit a PR, otherwise a snippet reproducing the problem would be good, i'm not sure if the bug is reproducible in https://github.com/gre/react-native-view-shot-example already

**Comment by gre** [comment] 2017-09-19 09:23
closing as I can't reproduce it. if you can and want to provide a fix, please provide a PR.

**Closed by gre** 2017-09-19 09:23 UTC

**Comment by Mitesh-2009** [comment] 2019-09-26 11:45
scroll view content no of items and capture a single image of the scroll view. Like...
![zoGHk](https://user-images.githubusercontent.com/34374930/65686096-310f4c80-e081-11e9-8ede-8040a83e539f.png)

**Comment by Mitesh-2009** [comment] 2019-09-27 07:16
scrollview inside flatlist then capture screenshot

**Comment by suman12-24** [comment] 2024-09-05 04:48
> scroll view content no of items and capture a single image of the scroll view. get image Like below... ![zoGHk](https://user-images.githubusercontent.com/34374930/65686096-310f4c80-e081-11e9-8ede-8040a83e539f.png)

can you give the source code?
