### ISSUE TITLE
Cannot read property 'captureRef' of undefined at captureRef

### ISSUE THREAD

**Issue by xiaoyongchen** [gre/react-native-view-shot#106] opened 2017-09-26 17:49 UTC
#### Version & Platform

```bash
npm ls react-native react-native-view-shot #<- PASTE CMD RESULT IN HERE
```

**Platform:** iOS? Android?

**Comment by gre** [comment] 2017-09-26 18:47
please fill the details about the version you use.
also a code snippet would help.

**Comment by gre** [comment] 2017-09-26 18:49
make sure to `react-native link react-native-view-shot`

**Comment by xiaoyongchen** [comment] 2017-09-27 02:00
hi
platform:ios
react-native:4.7.1
react-native-view-shot:2.1.0

**Comment by xiaoyongchen** [comment] 2017-09-27 02:00
rnpm-install info Android module react-native-view-shot is already linked
rnpm-install info iOS module react-native-view-shot is already linked

**Comment by xiaoyongchen** [comment] 2017-09-27 02:01
It doesn't work when I do this

**Comment by gre** [comment] 2017-09-27 05:03
the example app works fine. Mind sharing some code? Or a minimal app that reproduce the bug?

**Comment by serdarde** [comment] 2017-10-09 00:40
Hello, I get the same error. this is my package.json
```
  "dependencies": {
    "react": "16.0.0",
    "expo": "^21.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-view-shot": "^2.1.1",
  },
```

Platform: IOS 11

**result of** npm ls react-native react-native-view-shot:
├── react-native@0.48.4 
└── react-native-view-shot@2.1.1

**Comment by gre** [comment] 2017-10-09 07:30
mmh I suspect it's a version mismatch between react-native-view-shot and the current Expo native code of react-native-view-shot.
maybe @brentvatne can help? I'm not sure where to look at in Expo source code to see which version of this library should be used.

If you use Expo, maybe try with the v1 (that have different API, refer to readme)

now i'm not sure if @xiaoyongchen were using Expo too?

**Comment by brentvatne** [comment] 2017-10-09 19:22
@gre - ah we should update this in sdk22! totally slipped my mind. I'll add to things to do

**Comment by brentvatne** [comment] 2017-10-12 02:16
I forgot to mention one thing -- within Expo we changed the API for react-native-view-shot so you can just access it like this: https://docs.expo.io/versions/latest/sdk/take-snapshot-async.html

**Comment by brentvatne** [comment] 2017-10-12 02:19
also -- I don't think I will have time to update it for expo sdk22 because there have been some significant changes to this api and I'll need to think about how we want to pull them in

**Comment by gre** [comment] 2017-10-12 05:58
the main recent changes are:
- drop of support of "path" . but it does not look like it was even in Expo's takeSnapshotAsync
- the addition of `releaseCapture` (that allows to "free" a previously captured image – useful to not leak files when an app usecase is to capture a lot of things).
- `captureScreen`, a new method to capture the entire screen (not a given view)

**Comment by xiaoyongchen** [comment] 2017-10-14 06:11
ok，This is the configuration problem。

**Comment by pierretanguay** [comment] 2017-10-19 17:24
I have the same problem and can't make it work. Is there a simple sample code available?

**Comment by xiaoyongchen** [comment] 2017-10-20 02:18
@pierretanguay platform is ios or android ?

**Comment by pierretanguay** [comment] 2017-10-20 03:38
@xiaoyongchen I am on iOS.

**Comment by xiaoyongchen** [comment] 2017-10-20 13:00
@pierretanguay Follow the steps below
react-native link react-native-view-shot
ok

**Comment by liaquatkhan7** [comment] 2017-11-08 19:35
i am getting the same error i am using this in android app.  Here is the error that i am getting
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'captureRef' of undefined
TypeError: Cannot read property 'captureRef' of undefined

**Comment by macelii** [comment] 2017-11-09 04:24
I use react-native init to generate all projects and still facing this issue

**Comment by macelii** [comment] 2017-11-09 04:33
The error message is TypeError: undefined is not an object (evaluating 'RNViewShot.captureRef')

**Comment by macelii** [comment] 2017-11-09 05:05
I missed an output from console, it seems that the component is not linked correctly:
NativeModules.RNViewShot is undefined. Make sure the library is linked on the native side.
Despite I've already run react-native link react-native-view-shot

**Comment by macelii** [comment] 2017-11-09 05:09
For those who have similar issue:
Manually link the component solved the problem.

**Comment by liaquatkhan7** [comment] 2017-11-09 09:22
i linked it manually still giving me the same error from my phone

**Comment by macelii** [comment] 2017-11-10 07:41
The real reason for my issue is here:
https://github.com/facebook/react-native/issues/10494

I have several xcodeproj files in my ios root directory, react-native link returns a link success message but projects are not correctly linked, hence a manual installation solves the problem.

It has nothing to do with this repo though, this one is on react native itself.

**Comment by gre** [comment] 2017-11-10 08:01
thanks for investigating.

I've added this comment in the README: 
Make sure react-native-view-shot is correctly linked in XCode (might require a manual installation, refer to [React Native doc](https://facebook.github.io/react-native/docs/linking-libraries-ios.html)).

going to close this issue now :)

**Closed by gre** 2017-11-10 08:01 UTC

**Comment by helixbass** [comment] 2018-01-12 19:17
Don't really understand the mechanics, but I was running into the same error as @macelii (after having run `react-native link react-native-view-shot`) and found that running `pod install` fixed it

**Comment by MarkOSullivan94** [comment] 2018-04-25 10:52
@liaquatkhan7 did you find a fix? I'm experiencing the same issue

**Comment by Sergensen** [comment] 2018-06-02 12:18
Same issue

**Comment by PerspectivesLab** [comment] 2018-06-03 05:59
same issue on android, linked manually with:
`app/build.gradle : compile project(':react-native-view-shot')`
and in settings.gradle:
```
include ':react-native-view-shot'
project(':react-native-view-shot').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-view-shot/android')
```
how to resolve this ?

**Comment by calcazar** [comment] 2018-06-10 18:47
Can someone update the read me to show manual linking with Android and iOS?

**Comment by darrenmerrett** [comment] 2018-06-23 09:40
After spending 3 hours on this with my Android build I went back to basics, react-native unlink react-native-view-shot and then react-native link react-native-view-shot

iOS linked with no errors, Android threw an error  "It seems something went wrong while linking. Error: ENOENT: no such file or directory, open 'android/app/src/main/java/com/abc/def/MainApplication.java'. 

My directory structure is android/app/src/main/java/com/abc.def/MainApplication.java subtle difference.

So.... all I needed to do was add

import fr.greweb.reactnativeviewshot.RNViewShotPackage; // <- this

and 

      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNViewShotPackage(), // <- this

to MainApplication.java and it worked!

Hope this helps someone.

**Comment by Korno91** [comment] 2018-07-04 17:03
react-native-link doesnt work for android in my case, it only links IOS. Can you add manual installation on your docs?. When I add that import manually that you mentioned @darrenmerrett it tells me it "cannot find that symbol" pointing at that import. Had same problem with different lib b4, and the reason was that it was a wrong import

**Comment by RabbitJohn** [comment] 2018-10-11 02:32
@helixbass thanks for reminding me, I have resolved the problem '... of undefined' by reinstall pod

**Comment by hatiboy** [comment] 2018-11-30 05:29
Thank you so much @darrenmerrett . I have resolved the problem by your solution.

**Comment by mohamedabusrea** [comment] 2019-01-10 04:19
I'm using react-native (not Expo) and I had that error and when I tried to build the project from the android studio I got that error "Android dependency has a different version for the compile and runtime".

Solution: the solution in this page solved the problem for me [https://stackoverflow.com/questions/44653261/android-dependency-has-different-version-for-the-compile-and-runtime](this)

**Comment by ShridharCodewave** [comment] 2019-02-05 12:10
@PerspectivesLab did you find the solution? Iam facing the same issue on android.

**Comment by pssgo** [comment] 2019-07-26 09:10
i solve this problem in ios

try 

```shell
cd ios
pod install
```
